# ARRAY

## CREATING 1D ARRAY

In [3]:
from numpy import *

### 1. Using array()

In [2]:
a=array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
a=array([1, 2, 3],float)
print(a)

[1. 2. 3.]


In [5]:
a=array(['a', 'b','c'])
print(a)

['a' 'b' 'c']


In [9]:
a=array(['apple', 'ball','cat'])
print(a)

['apple' 'ball' 'cat']


### 2. Using linspace()

In [10]:
a=linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


### 3. Using logspace()

In [12]:
a=logspace(1,4,5)
print(a)

[   10.            56.23413252   316.22776602  1778.27941004
 10000.        ]


### 4. Using arange()

In [19]:
a=arange(0,10,3)
print(a)

[0 3 6 9]


In [17]:
a=arange(0,30)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [18]:
a=arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
a=arange(10,1,-1)
print(a)

[10  9  8  7  6  5  4  3  2]


### 5. Using zeros() and ones()

In [31]:
a=zeros(10,float)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
a=ones(10,int)
print(a)

[1 1 1 1 1 1 1 1 1 1]


### CREATING 2D ARRAYS

### 1. Using array()

In [30]:
a=array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


### 2. Using zeros() and ones()

In [33]:
a=zeros((2,3),float)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [36]:
a=zeros((4,3),int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [34]:
a=ones((4,3),float)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [37]:
a=ones((7,3),int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


### 3. Using eye()

In [40]:
a=eye(7,dtype=int)
print(a)

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


In [41]:
a=eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# MATRIX

## CREATING MATRIX

In [43]:
a=[[1,2,3],[4,5,6]]
m=matrix(a)
print(m)

[[1 2 3]
 [4 5 6]]


In [44]:
m=matrix([[1,2,3],[4,5,6]])
print(m)

[[1 2 3]
 [4 5 6]]


In [47]:
s='1 2 3; 4 5 6'
m=matrix(str)
print(m)

[[1 2 3]
 [4 5 6]]


In [46]:
m=matrix('1 2 3; 4 5 6')
print(m)

[[1 2 3]
 [4 5 6]]
