### Importing numpy

In [2]:
import numpy as np

### Creating array using numpy

**np.array()**<br>
creates array with values inside the bracket (it can be list, array, tuple, etc)

In [3]:
np.array([2,3,5])

array([2, 3, 5])

**np.zeroes(a,b)**<br>
create array with a rows and b columns with all values 0.0 (default is float)

In [4]:
np.zeros(3)

array([0., 0., 0.])

**np.ones(a,b)**<br>
create array with a rows and b columns with all values 1.0 (default is float)

In [5]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**np.full((a,b),y)**<br> 
create array with a rows and b column with all values y

In [6]:
x=np.full((7,13),0.5)
print(x)

[[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]]


### Attributes of numpy array
**arrayname.ndim**<br>
dimensions of array<br>
**arrayname.shape**<br>
number of rows and columns (rows,columns)<br>
**arrayname.size**<br>
number of elements of array<br>
**arrayname.itemsize**<br>
size of element in array<br>
**arrayname.dtype**<br>
datatype of element in array<br>
**arrayname.nbytes**<br>
number of bytes occupied by the array<br>

In [12]:
x=np.array([[2,3,6,7],[5,2,1,9]])
print("Array: \n",x)
print("Dimensions: ",x.ndim)
print("No. of rows and columns: ",x.shape)
print("Size of array: ",x.size)
print("Size of item: ",x.itemsize)
print("Datatype: ",x.dtype)
print("No. of bytes: ",x.nbytes)

Array: 
 [[2 3 6 7]
 [5 2 1 9]]
Dimensions:  2
No. of rows and columns:  (2, 4)
Size of array:  8
Size of item:  4
Datatype:  int32
No. of bytes:  32


In [14]:
print("Information about memory layout of array: ",x.flags)
print("Tuple of bytes to step in each dimension when traversing an array.",x.strides)
print("Python buffer object pointing to the start of the array's data.",x.data)
print("Base object if memory is from some other object.",x.base)

Information about memory layout of array:    C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

Tuple of bytes to step in each dimension when traversing an array. (16, 4)
Python buffer object pointing to the start of the array's data. <memory at 0x000001FE5B18E790>
Base object if memory is from some other object. None


In [27]:
y=np.array([[2+4j, 3+5j, 7+8j],[4+9j, 6j+2, 22]])
print("Transpose: \n",y.T)
print("Real part of array: \n",y.real)
print("Imaginary part of array: \n",y.imag)
print("A 1-D iterator over the array",y.flat)

Transpose: 
 [[ 2.+4.j  4.+9.j]
 [ 3.+5.j  2.+6.j]
 [ 7.+8.j 22.+0.j]]
Real part of array: 
 [[ 2.  3.  7.]
 [ 4.  2. 22.]]
Imaginary part of array: 
 [[4. 5. 8.]
 [9. 6. 0.]]
A 1-D iterator over the array <numpy.flatiter object at 0x000001FE5B548670>


### Concatenation

np.concatenate((a,b),axis=)<br>
a -> array1<br>
b -> array2<br>
axis=0 -> concatenate coloumnwise<br>
axis=1 -> concatenate rowwise


In [3]:
a=np.array([[2,3],[5,9]])
b=np.array([[6,4],[1,0]])
y=np.concatenate((a,b),axis=0)
x=np.concatenate((a,b),axis=1)
print("Columnwise concatenation: \n",x)
print("Rowwise concatenation: \n",y)

Columnwise concatenation: 
 [[2 3 6 4]
 [5 9 1 0]]
Rowwise concatenation: 
 [[2 3]
 [5 9]
 [6 4]
 [1 0]]


### Transpose
arrayname.transpose()

In [9]:
print("Array: \n",x)
print("Transpose: \n",x.transpose())

Array: 
 [[2 3 6 4]
 [5 9 1 0]]
Transpose: 
 [[2 5]
 [3 9]
 [6 1]
 [4 0]]


In [ ]:
#QUESTIONS
#random numbers in numpy follows which distribution?
# sum,prod,meam,std,var,min,max,argmin,argmax,median
#Significance of terms like std, var, mean, eigenvalues, eigenvectors, etc.
#broadcasting
